name: first-pipeline
on:
  push:
    branches: ["main"]
  work_dispatch:
jobs:
  first-pipeline:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
       - name: "Minha primeira ação"
         run: echo "Minha primeira acao" 
       - name: "Minha segunda acao"
         run: |
           echo "Minha segunda acao"
           echo "Parabens !!!" 
       - name: "Minha terceira acao"
         shell: python
         run: |
           variavel = "Hello Word Python"
           print(variavel)

              
                       
           

         
        
  
  
