name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-pipeline:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
       - name: "Minha primeira ação"
         run: echo "Minha primeira acao" 
       - name: "Minha segunda acao"
         run: |
           echo "Minha segunda acao"
           echo "Parabens !!!" 
       - name: "Minha terceira acao"
         shell: python
         run: |
           variavel = "Hello Word Python"
           print(variavel)
  second-pipeline:
    name: "Meu segundo job  - instalacao do NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificacao da versao do NodeJS atual"
        run: node --version
      - name: "Setting do NodeJS "
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"
      - name: "Verificacao da nova versao do NodeJS atual"
        run: node --version
        

    

              
                       
           

         
        
  
  
